export const enum CategoryFemale {
  outer = 'outer',
  vest = 'vest',
  dress = 'dress',
  top = 'top',
  pants = 'pants',
  skirt = 'skirt',
  bag = 'bag',
  shoes = 'shoes',
  accHat = 'accHat',
  accGlasses = 'accGlasses',
  accScarf = 'accScarf',
  accMuffler = 'accMuffler',
  accSocks = 'accSocks',
  accGloves = 'accGloves',
  random = 'random',
}
export const enum CategoryMan {
  outer = 'outer',
  vest = 'vest',
  top = 'top',
  pants = 'pants',
  suitjacket = 'suitjacket',
  suitvest = 'suitvest',
  suitshirts = 'suitshirts',
  suitpants = 'suitpants',
  suit = 'suit',
  shoes = 'shoes',
  bag = 'bag',
  accHat = 'accHat',
  accGlasses = 'accGlasses',
  accMuffler = 'accMuffler',
  accScarf = 'accScarf',
  accSocks = 'accSocks',
  random = 'random',
}
